#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api:
    prefix: /api
    resource: '../src/Controller'

document:
    type: rest
    resource: App\Controller\DocumentController
